

> Import libraries to use



In [1]:
import numpy as np

>  # Introduction to numpy (Skip if you already are familiar)

>> Creating a 1D array

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


>> Creating a 2D array


In [3]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


>> Creating an array full of zeros


In [4]:
a = np.zeros(shape=(10))
print(a)
a = np.zeros(shape=(5,2))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


>> Infinity in numpy

In [5]:
print(np.inf)

inf


>> Max and Argmax

In [6]:
a = np.array([2,1,4,3])
print(np.max(a))
print(np.argmax(a))

4
2


>> From list to Numpy

In [7]:
l = [1,2,3,4]
print(l)
print(np.asarray(l))

[1, 2, 3, 4]
[1 2 3 4]


>> Random in numpy

In [8]:
# Array of Random integers ranging from 1 to 10 (with any size you want)
a = np.random.randint(low=1, high=10, size=(5,2))
print(a)

# Array of random elements of a list with any size you want
a = np.random.choice([0,1,2], size=(2,))

[[5 8]
 [8 5]
 [9 7]
 [1 2]
 [7 4]]


>> Shapes in numpy

In [10]:
a = np.random.randint(low=1, high=5, size=(4,2))
print(a.shape)
print(a)

# Reshape a to a vector of shape = (8,1)
a = a.reshape((8,1))
print(a.shape)
print(a)

(4, 2)
[[2 3]
 [4 1]
 [3 4]
 [2 3]]
(8, 1)
[[2]
 [3]
 [4]
 [1]
 [3]
 [4]
 [2]
 [3]]


# Pre-defined utilities

In [11]:

int_to_char = {
    0 : 'u',
    1 : 'r',
    2 : 'd',
    3 : 'l'
}

policy_one_step_look_ahead = {
    0 : [-1,0],
    1 : [0,1],
    2 : [1,0],
    3 : [0,-1]
}

def policy_int_to_char(pi,n):

    pi_char = ['']

    for i in range(n):
        for j in range(n):

            if i == 0 and j == 0 or i == n-1 and j == n-1:

                continue

            pi_char.append(int_to_char[pi[i,j]])

    pi_char.append('')

    return np.asarray(pi_char).reshape(n,n)

# 1- Policy evaluation

In [ ]:
def policy_evaluation(n,pi,v,Gamma,threshhold):
  """
    This function should return the value function that follows the policy pi.
    Use the stopping criteria given in the problem statement.
  """
  while True:
    delta=0
    for i in range(n):
      for j in range(n):
        
        if(i==0 and j==0) or (i==n-1 and j==n-1): #skip eval for terminal states (might be useless)
          continue
        
        v_prev=v[i,j]
        action=pi[i,j]
        di,dj=policy_one_step_look_ahead[action]
        next_i,next_j=i+di,j+dj
        
        if 0<=next_i<n and 0<=next_j<n:
          reward=10 if (next_i==n-1 and next_j==n-1) else -1 # Reward change possible
          v[i,j]=reward+Gamma*v[next_i,next_j]
        
        delta=max(delta,abs(v_prev-v[i,j]))
        
    if delta<threshhold:
      break
  return v

# 2- Policy improvement

In [ ]:
def policy_improvement(n,pi,v,Gamma):
  """
    This function should return the new policy by acting in a greedy manner.
    The function should return as well a flag indicating if the output policy
    is the same as the input policy.

    Example:
      return new_pi, True if new_pi = pi for all states
      else return new_pi, False
  """
  pi_stable=True
  new_pi=np.copy(pi)
  
  for i in range(n):
    for j in range(n):
      if(i==0 and j==0) or (i==n-1 and j==n-1): #(might be useless)
          continue
        
      prev_action=pi[i,j]
      action_values=[]
      
      for action in range(4):
        di, dj=policy_one_step_look_ahead[action]
        next_i,next_j=i+di,j+dj
        
        if 0<=next_i<n and 0<=next_j<n:
          reward=10 if (next_i==n-1 and next_j==n-1) else -1 # Reward change possible
          action_value=reward+Gamma*v[next_i,next_j]
          action_values.append(action_value)
          
        else:
          action_values.append(-1+Gamma*v[i,j])
          
      best_action=np.argmax(action_values)
      new_pi[i,j]=best_action
      
      if best_action!=prev_action:
        pi_stable=False
        
  return new_pi,pi_stable

# 3- Policy Initialization

In [22]:
def policy_initialization(n):
  """
    This function should return the initial random policy for all states.
  """
  pi=np.random.choice([0, 1, 2, 3],size=(n,n))
  pi[0,0]=-1
  pi[n-1,n-1]=-1
  return pi

# 4- Policy Iteration algorithm

In [15]:
def policy_iteration(n,Gamma,threshhold):

    pi = policy_initialization(n=n)

    v = np.zeros(shape=(n,n))

    while True:

        v = policy_evaluation(n=n,v=v,pi=pi,threshhold=threshhold,Gamma=Gamma)

        pi , pi_stable = policy_improvement(n=n,pi=pi,v=v,Gamma=Gamma)

        if pi_stable:

            break

    return pi , v

# Main Code to Test

In [23]:
n = 4

Gamma = [0.8,0.9,1]

threshhold = 1e-4

for _gamma in Gamma:

    pi , v = policy_iteration(n=n,Gamma=_gamma,threshhold=threshhold)

    pi_char = policy_int_to_char(n=n,pi=pi)

    print()
    print("Gamma = ",_gamma)

    print()

    print(pi_char)

    print()
    print()

    print(v)



Gamma =  0.8

[['' 'r' 'r' 'd']
 ['r' 'r' 'r' 'd']
 ['r' 'r' 'r' 'd']
 ['r' 'r' 'r' '']]


[[ 0.     1.144  2.68   4.6  ]
 [ 1.144  2.68   4.6    7.   ]
 [ 2.68   4.6    7.    10.   ]
 [ 4.6    7.    10.     0.   ]]

Gamma =  0.9

[['' 'r' 'r' 'd']
 ['r' 'r' 'r' 'd']
 ['r' 'r' 'r' 'd']
 ['r' 'r' 'r' '']]


[[ 0.     3.122  4.58   6.2  ]
 [ 3.122  4.58   6.2    8.   ]
 [ 4.58   6.2    8.    10.   ]
 [ 6.2    8.    10.     0.   ]]

Gamma =  1

[['' 'r' 'r' 'd']
 ['r' 'r' 'r' 'd']
 ['r' 'r' 'r' 'd']
 ['r' 'r' 'r' '']]


[[ 0.  6.  7.  8.]
 [ 6.  7.  8.  9.]
 [ 7.  8.  9. 10.]
 [ 8.  9. 10.  0.]]
